import '../analyzer/field_inspector.dart';
import '../models/discovered_screen.dart';
import '../models/discovered_state.dart';
import '../models/type_info.dart';
import 'fixture_generator.dart';

/// Generates golden test files and fixture files from discovered screens and
/// states.
///
/// Produces two kinds of output:
/// 1. Fixture files - one per state class, with named fixture instances varying
///    one field at a time.
/// 2. Test files - one per screen, with testWidgets for each combo of
///    status x fixture x size x locale.
class GoldenTestGenerator {
  final List<(String name, int width, int height)> sizes;
  final List<String> locales;
  final String themeImport;
  final String themeVariable;
  final String l10nDelegatesImport;
  final String l10nDelegatesVariable;
  final String l10nSupportedLocalesVariable;

  final FieldInspector _fieldInspector = FieldInspector();
  final FixtureGenerator _fixtureGenerator = FixtureGenerator();

  GoldenTestGenerator({
    required this.sizes,
    required this.locales,
    required this.themeImport,
    required this.themeVariable,
    required this.l10nDelegatesImport,
    required this.l10nDelegatesVariable,
    required this.l10nSupportedLocalesVariable,
  });

  /// Generate a fixture file for a single [DiscoveredState].
  ///
  /// Returns the complete Dart file contents as a string.
  String generateFixtureFile(DiscoveredState state) {
    final buf = StringBuffer();
    final className = '${state.className}Fixtures';
    final dataFields = state.dataFields;

    // Header
    buf.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buf.writeln('// Generated by flutter_goldgen');
    buf.writeln();
    buf.writeln("import '${state.importUri}';");
    buf.writeln();

    buf.writeln('class $className {');

    // Baseline
    buf.writeln('  // Baseline (all normal defaults)');
    buf.writeln('  static final baseline = ${state.className}();');
    buf.writeln();

    // Track all fixture names for the `all` list
    final allNames = <String>['baseline'];

    // Vary one field at a time
    for (final field in dataFields) {
      final typeInfo = _fieldInspector.resolveField(field);
      final values = _fixtureGenerator.generateValues(typeInfo);
      final labels = _labelsForValues(values, typeInfo);

      buf.writeln('  // Vary ${field.name} field');

      for (var i = 0; i < values.length; i++) {
        final fixtureName = '${field.name}_${labels[i]}';
        allNames.add(fixtureName);
        buf.writeln(
          '  static final $fixtureName = ${state.className}(${field.name}: ${values[i]});',
        );
      }
      buf.writeln();
    }

    // all list
    buf.writeln('  static final all = [');
    for (final name in allNames) {
      buf.writeln('    $name,');
    }
    buf.writeln('  ];');

    buf.writeln('}');

    return buf.toString();
  }

  /// Generate a test file for a single [DiscoveredScreen].
  ///
  /// [states] maps state class names to their [DiscoveredState].
  /// Returns the complete Dart file contents as a string.
  String generateTestFile(
    DiscoveredScreen screen,
    Map<String, DiscoveredState> states,
  ) {
    final buf = StringBuffer();
    final screenNameSnake = _toSnakeCase(screen.className);

    // Header
    buf.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buf.writeln('// Generated by flutter_goldgen');
    buf.writeln();

    // Imports
    buf.writeln("import 'package:flutter_test/flutter_test.dart';");
    buf.writeln("import 'package:flutter/material.dart';");
    buf.writeln("import 'package:flutter_bloc/flutter_bloc.dart';");
    buf.writeln("import 'package:mocktail/mocktail.dart';");
    buf.writeln("import '$themeImport';");
    buf.writeln("import '$l10nDelegatesImport';");
    buf.writeln("import '${screen.importUri}';");

    // Import states and their fixture files
    for (final binding in screen.cubitBindings) {
      final state = states[binding.stateClassName];
      if (state != null) {
        buf.writeln("import '${state.importUri}';");
      }
      // Fixture import — assume fixture file is alongside the test file
      final fixtureFileName =
          '${_toSnakeCase(binding.stateClassName)}_fixtures.dart';
      buf.writeln("import '$fixtureFileName';");
    }
    buf.writeln();

    // Mock cubit classes
    for (final binding in screen.cubitBindings) {
      final state = states[binding.stateClassName];
      final stateClass = binding.stateClassName;
      final cubitClass = binding.cubitClassName;
      buf.writeln(
          'class Mock$cubitClass extends Mock implements $cubitClass {');
      buf.writeln('  Mock$cubitClass(this._state);');
      buf.writeln('  final $stateClass _state;');
      buf.writeln();
      buf.writeln('  @override');
      buf.writeln('  $stateClass get state => _state;');
      buf.writeln();
      buf.writeln('  @override');
      buf.writeln(
          '  Stream<$stateClass> get stream => Stream.value(_state);');
      buf.writeln('}');
      buf.writeln();
    }

    // main()
    buf.writeln('void main() {');

    // For each cubit binding, generate test loops
    for (final binding in screen.cubitBindings) {
      final state = states[binding.stateClassName];
      if (state == null) continue;

      final fixtureClass = '${binding.stateClassName}Fixtures';
      final cubitClass = binding.cubitClassName;

      buf.writeln(
          '  // Vary $cubitClass states, hold others at default');

      for (final (sizeName, width, height) in sizes) {
        for (final locale in locales) {
          final folderPrefix = '${sizeName}_$locale';
          buf.writeln(
              '  for (final fixture in $fixtureClass.all) {');
          buf.writeln(
              '    for (final status in UiFlowStatus.values) {');
          buf.writeln('      testWidgets(');
          buf.writeln(
              "        '${screenNameSnake}_${_toSnakeCase(binding.stateClassName)}_\${status.name}_\${fixture.hashCode}',");
          buf.writeln('        (tester) async {');
          buf.writeln(
              '          tester.view.physicalSize = const Size($width, $height);');
          buf.writeln(
              '          tester.view.devicePixelRatio = 1.0;');
          buf.writeln();
          buf.writeln('          await tester.pumpWidget(');
          buf.writeln('            MaterialApp(');
          buf.writeln('              theme: $themeVariable,');
          buf.writeln(
              "              locale: const Locale('$locale'),");
          buf.writeln(
              '              localizationsDelegates: $l10nDelegatesVariable,');
          buf.writeln(
              '              supportedLocales: $l10nSupportedLocalesVariable,');

          // Build providers list
          if (screen.cubitBindings.length == 1) {
            buf.writeln(
                '              home: BlocProvider<$cubitClass>.value(');
            buf.writeln('                value: Mock$cubitClass(');
            buf.writeln(
                "                  fixture.copyWith(status: status, error: status == UiFlowStatus.failure ? Exception('Test error') : null),");
            buf.writeln('                ),');
            buf.writeln(
                '                child: const ${screen.className}(),');
            buf.writeln('              ),');
          } else {
            buf.writeln('              home: MultiBlocProvider(');
            buf.writeln('                providers: [');
            for (final b in screen.cubitBindings) {
              if (b.cubitClassName == cubitClass) {
                buf.writeln(
                    '                  BlocProvider<${b.cubitClassName}>.value(');
                buf.writeln(
                    '                    value: Mock${b.cubitClassName}(');
                buf.writeln(
                    "                      fixture.copyWith(status: status, error: status == UiFlowStatus.failure ? Exception('Test error') : null),");
                buf.writeln('                    ),');
                buf.writeln('                  ),');
              } else {
                final otherFixtureClass =
                    '${b.stateClassName}Fixtures';
                buf.writeln(
                    '                  BlocProvider<${b.cubitClassName}>.value(');
                buf.writeln(
                    '                    value: Mock${b.cubitClassName}($otherFixtureClass.baseline),');
                buf.writeln('                  ),');
              }
            }
            buf.writeln('                ],');
            buf.writeln(
                '                child: const ${screen.className}(),');
            buf.writeln('              ),');
          }

          buf.writeln('            ),');
          buf.writeln('          );');
          buf.writeln('          await tester.pumpAndSettle();');
          buf.writeln();
          buf.writeln('          await expectLater(');
          buf.writeln(
              '            find.byType(${screen.className}),');
          buf.writeln(
              "            matchesGoldenFile('$folderPrefix/${screenNameSnake}_${_toSnakeCase(binding.stateClassName)}_\${status.name}_\${fixture.hashCode}.png'),");
          buf.writeln('          );');
          buf.writeln();
          buf.writeln(
              '          addTearDown(() => tester.view.resetPhysicalSize());');
          buf.writeln('        },');
          buf.writeln('      );');
          buf.writeln('    }');
          buf.writeln('  }');
        }
      }
    }

    buf.writeln('}');

    return buf.toString();
  }

  /// Generate labels for edge case values based on type info.
  List<String> _labelsForValues(List<String> values, TypeInfo typeInfo) {
    final labels = <String>[];
    for (final value in values) {
      labels.add(_labelForValue(value, typeInfo));
    }
    return labels;
  }

  String _labelForValue(String value, TypeInfo typeInfo) {
    if (value == 'null') return 'null';
    if (value == 'true') return 'true';
    if (value == 'false') return 'false';
    if (value == '0' || value == '0.0') return 'zero';
    if (value == '1' || value == '1.5') return 'one';
    if (value == '999999' || value == '999999.99') return 'large';
    if (value == "''") return 'empty';
    if (value == "'A'") return 'single';
    if (value == "'Test string'") return 'normal';
    if (value.contains('* 200')) return 'long';
    if (value.contains('[]') || value.contains('{}')) return 'empty';
    if (value.contains('List.filled')) return 'large';
    if (value.startsWith('[') || value.startsWith('{')) return 'single';
    if (value.contains('DateTime.now')) return 'now';
    if (value.contains('DateTime(')) return 'fixed';
    if (value.contains('.')) {
      // Enum value like MyEnum.valueA
      final enumVal = value.split('.').last;
      return enumVal;
    }
    if (value.endsWith('()')) return 'default';
    return 'v${value.hashCode.abs()}';
  }

  String _toSnakeCase(String input) {
    final buf = StringBuffer();
    for (var i = 0; i < input.length; i++) {
      final char = input[i];
      if (char == char.toUpperCase() && char != char.toLowerCase()) {
        if (i > 0) buf.write('_');
        buf.write(char.toLowerCase());
      } else {
        buf.write(char);
      }
    }
    return buf.toString();
  }
}
