name: koinon_index_content_server
description: Starting point for a Serverpod module.

environment:
  sdk: '^3.8.0'

resolution: workspace

dependencies:
  serverpod: 3.4.5
  koinon_index_core_server:
    path: ../../koinon_index_core/koinon_index_core_server
  dart_git:
    path: ../../dart_git
  dart_koinon:
    path: ../../dart_koinon

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  serverpod_test: 3.4.5
  test: ^1.25.5
