name: _
publish_to: none

environment:
  sdk: '^3.8.0'

workspace:
  - achaean_client
  - achaean_server
  - achaean_flutter
  - dart_git
  - dart_koinon
  - flutter_adaptable_group
dependency_overrides:
  crypto: ^3.0.3
  flutter_secure_storage: ^10.0.0

