import 'package:dart_git/dart_git.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:flutter/material.dart';
import 'package:cubit_ui_flow/cubit_ui_flow.dart' as cubit_ui_flow;
import 'package:achaean_client/achaean_client.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:serverpod_flutter/serverpod_flutter.dart';
import '../app_router.dart';
import '../core/config/app_config.dart';
import '../core/services/flutter_secure_storage_adapter.dart';
import '../core/services/git_service.dart';
import '../core/services/i_git_service.dart';
import '../core/services/i_key_service.dart';
import '../core/services/i_signing_service.dart';
import '../core/services/key_service.dart';
import '../core/services/secure_preferences.dart';
import '../core/services/koinon_key_manager.dart';
import '../core/services/signing_service.dart';
import '../features/account_creation/cubit/account_creation_cubit.dart';
import '../features/account_creation/services/account_creation_service.dart';
import '../features/account_creation/services/i_account_creation_service.dart';
import '../features/post_creation/cubit/own_posts_cubit.dart';
import '../features/post_creation/cubit/post_creation_cubit.dart';
import '../features/post_creation/services/feed_generation_service.dart';
import '../features/post_creation/services/i_feed_generation_service.dart';
import '../features/post_creation/services/i_post_creation_service.dart';
import '../features/post_creation/services/i_post_signing_service.dart';
import '../features/post_creation/services/post_creation_service.dart';
import '../features/post_creation/services/post_signing_service.dart';
import '../features/flag/services/i_flag_service.dart';
import '../features/flag/services/flag_service.dart';
import '../features/flag/cubit/flag_cubit.dart';
import '../features/trust/services/i_trust_service.dart';
import '../features/trust/services/trust_service.dart';
import '../features/trust/cubit/trust_cubit.dart';
import '../features/polis/services/i_polis_service.dart';
import '../features/polis/services/polis_service.dart';
import '../features/polis/cubit/polis_cubit.dart';
import '../features/inspection/services/i_repo_inspection_service.dart';
import '../features/inspection/services/repo_inspection_service.dart';
import '../features/inspection/cubit/repo_inspection_cubit.dart';
import '../features/agora/services/i_post_reading_service.dart';
import '../features/agora/services/post_reading_service.dart';
import '../features/agora/services/i_agora_service.dart';
import '../features/agora/services/agora_service.dart';
import '../features/agora/services/git_backed_agora_service.dart';
import '../features/agora/services/i_polis_query_service.dart';
import '../features/agora/services/polis_query_service.dart';
import '../features/agora/services/i_user_query_service.dart';
import '../features/agora/services/user_query_service.dart';
import '../features/agora/services/i_voucher_review_service.dart';
import '../features/agora/services/voucher_review_service.dart';
import '../features/agora/cubit/agora_cubit.dart';
import '../features/agora/cubit/polis_discovery_cubit.dart';
import '../features/agora/cubit/voucher_review_cubit.dart';
import '../features/personal_feed/cubit/personal_feed_cubit.dart';
import '../features/personal_feed/services/post_content_cache.dart';
import 'bootstrap.config.dart';

/// Global service locator instance

final GetIt getIt = GetIt.instance;

/// Configures all dependency injection bindings.
/// Generated by build_runner from @injectable and @module annotations.
@InjectableInit()
void configureDependencies() {
  getIt.init();
}

/// Bootstraps the entire application.
///
/// Call this once from main() before runApp().
Future<void> bootstrap() async {
  debugPrint('Bootstrap: Starting...');

  try {
    // 1. Configure all injectable dependencies (includes InjectionModule)
    debugPrint('Bootstrap: Configuring dependencies...');
    configureDependencies();
    debugPrint('Bootstrap: Dependencies configured');

    // 2. Register services with complex dependencies
    debugPrint('Bootstrap: Registering core services...');
    _registerCoreServices();
    debugPrint('Bootstrap: Core services registered');

    // 3. Initialize Serverpod client (if index server URL is configured)
    debugPrint('Bootstrap: Initializing Serverpod client...');
    final prefs = getIt<SecurePreferences>();
    final indexServerUrl = await prefs.getIndexServerUrl();
    if (indexServerUrl != null) {
      final keyManager = KoinonKeyManager(getIt<IKeyService>());
      // ignore: deprecated_member_use
      final client = Client(
        indexServerUrl,
        authenticationKeyManager: keyManager,
      )..connectivityMonitor = FlutterConnectivityMonitor();
      getIt.registerSingleton<Client>(client);
      debugPrint('Bootstrap: Serverpod client initialized at $indexServerUrl');
    } else {
      debugPrint('Bootstrap: No index server URL configured, skipping Serverpod client');
    }

    // 3.5 Register query services
    if (getIt.isRegistered<Client>()) {
      debugPrint('Bootstrap: Registering Serverpod query services...');
      _registerServerpodQueryServices();
      debugPrint('Bootstrap: Serverpod query services registered');
    } else {
      debugPrint('Bootstrap: Demo mode — registering git-backed services...');
      _registerDemoServices();
      debugPrint('Bootstrap: Demo services registered');
    }

    // 3.6 Register feed services (always — work with both Serverpod and demo mode)
    debugPrint('Bootstrap: Registering feed services...');
    _registerFeedServices();
    debugPrint('Bootstrap: Feed services registered');

    // 4. Register UI flow service (depends on localization/feedback/loading)
    debugPrint('Bootstrap: Registering UI flow service...');
    _registerUiFlowService();
    debugPrint('Bootstrap: UI flow service registered');

    // 5. Check if user has an account (keypair exists)
    debugPrint('Bootstrap: Checking account status...');
    final hasAccount = await getIt<IKeyService>().hasKeypair();
    AppRouter.setHasAccount(hasAccount);
    debugPrint('Bootstrap: Account exists: $hasAccount');

    // 6. Configure ErrorPrivserver for privacy-preserving error reporting
    debugPrint('Bootstrap: Configuring ErrorPrivserver...');
    _configureErrorPrivserver();
    debugPrint('Bootstrap: ErrorPrivserver configured');

    debugPrint('Bootstrap: Complete');
  } catch (e, stack) {
    debugPrint('Bootstrap: FAILED - $e');
    debugPrint('Bootstrap: Stack trace:\n$stack');
    rethrow;
  }
}

/// Registers services that have complex/manual dependencies.
/// This is the ONLY place in the Flutter app that imports Forgejo-specific code.
void _registerCoreServices() {
  final secureStorage = getIt<FlutterSecureStorage>();
  final prefs = SecurePreferences(FlutterSecureStorageAdapter(secureStorage));
  getIt.registerSingleton<SecurePreferences>(prefs);

  // Git client factory — dispatches to the right IGitClient by host type
  getIt.registerSingleton<GitClientFactory>(({
    required String baseUrl,
    required IGitAuth auth,
    required GitHostType hostType,
  }) {
    return switch (hostType) {
      GitHostType.forgejo ||
      GitHostType.gitea ||
      GitHostType.codeberg =>
        ForgejoClient(baseUrl: baseUrl, auth: auth),
      GitHostType.github => throw UnimplementedError('GitHub support coming'),
      GitHostType.gitlab => throw UnimplementedError('GitLab support coming'),
    };
  });

  // Key management service
  getIt.registerLazySingleton<IKeyService>(
    () => KeyService(prefs),
  );

  // Git service (manages IGitClient lifecycle)
  getIt.registerLazySingleton<IGitService>(
    () => GitService(getIt<GitClientFactory>(), prefs),
  );

  // OAuth service (Forgejo/Gitea PKCE flow)
  getIt.registerLazySingleton<IGitOAuth>(
    () => ForgejoOAuth(),
  );

  // Account creation orchestrator
  getIt.registerLazySingleton<IAccountCreationService>(
    () => AccountCreationService(
      getIt<IKeyService>(),
      getIt<IGitOAuth>(),
      getIt<IGitService>(),
      getIt<SecurePreferences>(),
    ),
  );

  // Signing service (shared canonical-JSON signer)
  getIt.registerLazySingleton<ISigningService>(
    () => SigningService(getIt<IKeyService>()),
  );

  // Post signing service (delegates to ISigningService)
  getIt.registerLazySingleton<IPostSigningService>(
    () => PostSigningService(getIt<ISigningService>()),
  );

  // Feed generation service
  getIt.registerLazySingleton<IFeedGenerationService>(
    () => FeedGenerationService(getIt<IGitService>()),
  );

  // Post creation orchestrator
  getIt.registerLazySingleton<IPostCreationService>(
    () => PostCreationService(
      getIt<IGitService>(),
      getIt<IPostSigningService>(),
      getIt<IFeedGenerationService>(),
    ),
  );

  // Public (unauthenticated) git client factory for reading foreign repos
  getIt.registerSingleton<PublicGitClientFactory>(({
    required String baseUrl,
    required GitHostType hostType,
  }) {
    return getIt<GitClientFactory>()(
      baseUrl: baseUrl,
      auth: const GitPublicAuth(),
      hostType: hostType,
    );
  });

  // Flag service
  getIt.registerLazySingleton<IFlagService>(
    () => FlagService(getIt<IGitService>()),
  );

  // Trust service
  getIt.registerLazySingleton<ITrustService>(
    () => TrustService(
      getIt<IGitService>(),
      getIt<ISigningService>(),
      getIt<PublicGitClientFactory>(),
    ),
  );

  // Polis service
  getIt.registerLazySingleton<IPolisService>(
    () => PolisService(
      getIt<IGitService>(),
      getIt<ISigningService>(),
      getIt<PublicGitClientFactory>(),
    ),
  );

  // Repo inspection service
  getIt.registerLazySingleton<IRepoInspectionService>(
    () => RepoInspectionService(
      getIt<IGitService>(),
      getIt<PublicGitClientFactory>(),
    ),
  );

  // Cubits (factory — new instance per use)
  getIt.registerFactory<AccountCreationCubit>(
    () => AccountCreationCubit(getIt<IAccountCreationService>()),
  );
  getIt.registerFactory<PostCreationCubit>(
    () => PostCreationCubit(getIt<IPostCreationService>()),
  );
  getIt.registerFactory<OwnPostsCubit>(
    () => OwnPostsCubit(getIt<IPostCreationService>()),
  );

  // Phase 2 cubits
  getIt.registerFactory<TrustCubit>(
    () => TrustCubit(getIt<ITrustService>()),
  );
  getIt.registerFactory<FlagCubit>(
    () => FlagCubit(getIt<IFlagService>()),
  );
  getIt.registerFactory<PolisCubit>(
    () => PolisCubit(getIt<IPolisService>()),
  );
  getIt.registerFactory<RepoInspectionCubit>(
    () => RepoInspectionCubit(getIt<IRepoInspectionService>()),
  );
}

void _registerServerpodQueryServices() {
  final client = getIt<Client>();

  // Serverpod query services
  getIt.registerLazySingleton<IAgoraService>(
    () => AgoraService(client),
  );
  getIt.registerLazySingleton<IPolisQueryService>(
    () => PolisQueryService(client),
  );
  getIt.registerLazySingleton<IUserQueryService>(
    () => UserQueryService(client),
  );
  getIt.registerLazySingleton<IVoucherReviewService>(
    () => VoucherReviewService(client),
  );

  // Query cubits
  getIt.registerFactory<AgoraCubit>(
    () => AgoraCubit(
      getIt<IAgoraService>(),
      getIt<IPolisQueryService>(),
    ),
  );
  getIt.registerFactory<PolisDiscoveryCubit>(
    () => PolisDiscoveryCubit(getIt<IPolisQueryService>()),
  );
  getIt.registerFactory<VoucherReviewCubit>(
    () => VoucherReviewCubit(getIt<IVoucherReviewService>()),
  );
}

/// Registers git-backed services for demo mode (no Serverpod index server).
void _registerDemoServices() {
  if (AppConfig.hasGuestMode) {
    // Guest mode — read from public repo without authentication
    getIt.registerLazySingleton<IAgoraService>(
      () => GitBackedAgoraService.guest(
        repoUrl: AppConfig.guestRepoUrl,
        publicClientFactory: getIt<PublicGitClientFactory>(),
      ),
    );
  } else {
    // Authenticated demo mode — read from user's own repo
    getIt.registerLazySingleton<IAgoraService>(
      () => GitBackedAgoraService(
        getIt<IGitService>(),
        getIt<IKeyService>(),
      ),
    );
  }
}

/// Registers feed services that work in both Serverpod and demo mode.
void _registerFeedServices() {
  // Post reading service (reads from git repos — always git-based)
  getIt.registerLazySingleton<IPostReadingService>(
    () => PostReadingService(
      getIt<PublicGitClientFactory>(),
      GitHostType.forgejo,
    ),
  );

  // Post content cache (singleton — shared between feed and detail)
  getIt.registerLazySingleton<PostContentCache>(
    () => PostContentCache(getIt<IPostReadingService>()),
  );

  // Personal feed cubit
  getIt.registerFactory<PersonalFeedCubit>(
    () => PersonalFeedCubit(
      getIt<IAgoraService>(),
      getIt<PostContentCache>(),
    ),
  );
}

void _registerUiFlowService() {
  if (!getIt.isRegistered<cubit_ui_flow.IUiFlowService>()) {
    getIt.registerLazySingleton<cubit_ui_flow.IUiFlowService>(
      () => cubit_ui_flow.UiFlowService(
        localization: getIt<cubit_ui_flow.ILocalizationService>(),
        feedback: getIt<cubit_ui_flow.IFeedbackService>(),
        loading: getIt<cubit_ui_flow.ILoadingService>(),
      ),
    );
  }
}

/// Configure ErrorPrivserver for privacy-preserving error reporting.
void _configureErrorPrivserver() {
  // Note: Actual configuration requires repository implementations.
  // This is a placeholder for where you would wire up your error reporting.
  // See quanitya example for full implementation with ErrorBoxRepository.
  debugPrint('ErrorPrivserver: Initialization placeholder');
}
