import 'package:dart_git/dart_git.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:flutter/material.dart';
import 'package:cubit_ui_flow/cubit_ui_flow.dart' as cubit_ui_flow;
import 'package:achaean_client/achaean_client.dart';
import 'package:serverpod_flutter/serverpod_flutter.dart';
import 'package:serverpod_auth_idp_flutter/serverpod_auth_idp_flutter.dart';

import '../core/services/git_service.dart';
import '../core/services/i_git_service.dart';
import '../core/services/i_key_service.dart';
import '../core/services/i_serverpod_auth_service.dart';
import '../core/services/i_signing_service.dart';
import '../core/services/key_service.dart';
import '../core/services/serverpod_auth_service.dart';
import '../core/services/signing_service.dart';
import '../features/account_creation/cubit/account_creation_cubit.dart';
import '../features/account_creation/services/account_creation_service.dart';
import '../features/account_creation/services/i_account_creation_service.dart';
import '../features/post_creation/cubit/own_posts_cubit.dart';
import '../features/post_creation/cubit/post_creation_cubit.dart';
import '../features/post_creation/services/feed_generation_service.dart';
import '../features/post_creation/services/i_feed_generation_service.dart';
import '../features/post_creation/services/i_post_creation_service.dart';
import '../features/post_creation/services/i_post_signing_service.dart';
import '../features/post_creation/services/post_creation_service.dart';
import '../features/post_creation/services/post_signing_service.dart';
import '../features/flag/services/i_flag_service.dart';
import '../features/flag/services/flag_service.dart';
import '../features/flag/cubit/flag_cubit.dart';
import '../features/trust/services/i_trust_service.dart';
import '../features/trust/services/trust_service.dart';
import '../features/trust/cubit/trust_cubit.dart';
import '../features/polis/services/i_polis_service.dart';
import '../features/polis/services/polis_service.dart';
import '../features/polis/cubit/polis_cubit.dart';
import '../features/inspection/services/i_repo_inspection_service.dart';
import '../features/inspection/services/repo_inspection_service.dart';
import '../features/inspection/cubit/repo_inspection_cubit.dart';
import 'bootstrap.config.dart';

/// Global service locator instance

final GetIt getIt = GetIt.instance;

/// Configures all dependency injection bindings.
/// Generated by build_runner from @injectable and @module annotations.
@InjectableInit()
void configureDependencies() {
  getIt.init();
}

/// Bootstraps the entire application.
///
/// Call this once from main() before runApp().
Future<void> bootstrap() async {
  debugPrint('Bootstrap: Starting...');

  try {
    // 1. Configure all injectable dependencies (includes InjectionModule)
    debugPrint('Bootstrap: Configuring dependencies...');
    configureDependencies();
    debugPrint('Bootstrap: Dependencies configured');

    // 2. Register services with complex dependencies
    debugPrint('Bootstrap: Registering core services...');
    _registerCoreServices();
    debugPrint('Bootstrap: Core services registered');

    // 3. Initialize Serverpod client
    debugPrint('Bootstrap: Initializing Serverpod client...');
    final serverUrl = await getServerUrl();
    final client = Client(serverUrl)
      ..connectivityMonitor = FlutterConnectivityMonitor()
      ..authSessionManager = FlutterAuthSessionManager();
    client.auth.initialize();
    getIt.registerSingleton<Client>(client);
    debugPrint('Bootstrap: Serverpod client initialized');

    // 4. Register UI flow service (depends on localization/feedback/loading)
    debugPrint('Bootstrap: Registering UI flow service...');
    _registerUiFlowService();
    debugPrint('Bootstrap: UI flow service registered');

    // 5. Configure ErrorPrivserver for privacy-preserving error reporting
    debugPrint('Bootstrap: Configuring ErrorPrivserver...');
    _configureErrorPrivserver();
    debugPrint('Bootstrap: ErrorPrivserver configured');

    debugPrint('Bootstrap: Complete');
  } catch (e, stack) {
    debugPrint('Bootstrap: FAILED - $e');
    debugPrint('Bootstrap: Stack trace:\n$stack');
    rethrow;
  }
}

/// Registers services that have complex/manual dependencies.
/// This is the ONLY place in the Flutter app that imports Forgejo-specific code.
void _registerCoreServices() {
  final storage = getIt<FlutterSecureStorage>();

  // Git client factory — dispatches to the right IGitClient by host type
  getIt.registerSingleton<GitClientFactory>(({
    required String baseUrl,
    required IGitAuth auth,
    required GitHostType hostType,
  }) {
    return switch (hostType) {
      GitHostType.forgejo ||
      GitHostType.gitea ||
      GitHostType.codeberg =>
        ForgejoClient(baseUrl: baseUrl, auth: auth),
      GitHostType.github => throw UnimplementedError('GitHub support coming'),
    };
  });

  // Key management service
  getIt.registerLazySingleton<IKeyService>(
    () => KeyService(storage),
  );

  // Git service (manages IGitClient lifecycle)
  getIt.registerLazySingleton<IGitService>(
    () => GitService(getIt<GitClientFactory>(), storage),
  );

  // Account creation orchestrator
  getIt.registerLazySingleton<IAccountCreationService>(
    () => AccountCreationService(
      getIt<IKeyService>(),
      getIt<IGitRegistration>(),
      getIt<IGitService>(),
    ),
  );

  // Signing service (shared canonical-JSON signer)
  getIt.registerLazySingleton<ISigningService>(
    () => SigningService(getIt<IKeyService>()),
  );

  // Serverpod auth header service
  getIt.registerLazySingleton<IServerpodAuthService>(
    () => ServerpodAuthService(getIt<IKeyService>()),
  );

  // Post signing service (delegates to ISigningService)
  getIt.registerLazySingleton<IPostSigningService>(
    () => PostSigningService(getIt<ISigningService>()),
  );

  // Feed generation service
  getIt.registerLazySingleton<IFeedGenerationService>(
    () => FeedGenerationService(getIt<IGitService>()),
  );

  // Post creation orchestrator
  getIt.registerLazySingleton<IPostCreationService>(
    () => PostCreationService(
      getIt<IGitService>(),
      getIt<IPostSigningService>(),
      getIt<IFeedGenerationService>(),
    ),
  );

  // Public (unauthenticated) git client factory for reading foreign repos
  getIt.registerSingleton<PublicGitClientFactory>(({
    required String baseUrl,
    required GitHostType hostType,
  }) {
    return getIt<GitClientFactory>()(
      baseUrl: baseUrl,
      auth: const GitPublicAuth(),
      hostType: hostType,
    );
  });

  // Flag service
  getIt.registerLazySingleton<IFlagService>(
    () => FlagService(getIt<IGitService>()),
  );

  // Trust service
  getIt.registerLazySingleton<ITrustService>(
    () => TrustService(
      getIt<IGitService>(),
      getIt<ISigningService>(),
      getIt<PublicGitClientFactory>(),
    ),
  );

  // Polis service
  getIt.registerLazySingleton<IPolisService>(
    () => PolisService(
      getIt<IGitService>(),
      getIt<ISigningService>(),
      getIt<PublicGitClientFactory>(),
    ),
  );

  // Repo inspection service
  getIt.registerLazySingleton<IRepoInspectionService>(
    () => RepoInspectionService(
      getIt<IGitService>(),
      getIt<PublicGitClientFactory>(),
    ),
  );

  // Cubits (factory — new instance per use)
  getIt.registerFactory<AccountCreationCubit>(
    () => AccountCreationCubit(getIt<IAccountCreationService>()),
  );
  getIt.registerFactory<PostCreationCubit>(
    () => PostCreationCubit(getIt<IPostCreationService>()),
  );
  getIt.registerFactory<OwnPostsCubit>(
    () => OwnPostsCubit(getIt<IPostCreationService>()),
  );

  // Phase 2 cubits
  getIt.registerFactory<TrustCubit>(
    () => TrustCubit(getIt<ITrustService>()),
  );
  getIt.registerFactory<FlagCubit>(
    () => FlagCubit(getIt<IFlagService>()),
  );
  getIt.registerFactory<PolisCubit>(
    () => PolisCubit(getIt<IPolisService>()),
  );
  getIt.registerFactory<RepoInspectionCubit>(
    () => RepoInspectionCubit(getIt<IRepoInspectionService>()),
  );
}

void _registerUiFlowService() {
  if (!getIt.isRegistered<cubit_ui_flow.IUiFlowService>()) {
    getIt.registerLazySingleton<cubit_ui_flow.IUiFlowService>(
      () => cubit_ui_flow.UiFlowService(
        localization: getIt<cubit_ui_flow.ILocalizationService>(),
        feedback: getIt<cubit_ui_flow.IFeedbackService>(),
        loading: getIt<cubit_ui_flow.ILoadingService>(),
      ),
    );
  }
}

/// Configure ErrorPrivserver for privacy-preserving error reporting.
void _configureErrorPrivserver() {
  // Note: Actual configuration requires repository implementations.
  // This is a placeholder for where you would wire up your error reporting.
  // See quanitya example for full implementation with ErrorBoxRepository.
  debugPrint('ErrorPrivserver: Initialization placeholder');
}
